### ISSUE TITLE
The example doesn't work in Firefox

### ISSUE THREAD

**Issue by justinmc** [oblador/angular-parallax#13]
The [example](http://durated.github.io/angular-parallax/) doesn't work for me in Firefox, it just shows static images.  Is this intended or a recent break?  I saw older issues about IE but not Firefox.

**Comment by oblador** [comment]
Works fine on 30.0 on OSX. What are you using?

**Comment by justinmc** [comment]
Thanks for the quick response.  I'm on 30.0 on OSX :(

In my console I'm seeing `"Error: h is undefined` in angular.min.js if that helps.  Weird.

**Comment by oblador** [comment]
Tried it in a private window and it works the same. You're not using some kind of adblocker etc?

**Comment by oblador** [comment]
Also tried in browserstack which works.

**Comment by justinmc** [comment]
I am using ad block, but disabling it didn't fix the issue.

Whelp it sounds like it's something weird with my setup and you can probably close the issue...  I'll try to check on another computer later and post back if I figure out what's going on though.

**Comment by oblador** [comment]
Bumped angular and made the demo protocol agnostic (ie it should work fine over https aswell as http). Working now? Does it work when you download the project and try the example locally?

**Comment by justinmc** [comment]
It works!  Strange bug.  Thank you for getting back to me.  You should probably update the github.io example when you get a chance too: http://durated.github.io/angular-parallax/

**Comment by oblador** [comment]
I did change the demo :-) Still doesn't work?

**Comment by justinmc** [comment]
No, the demo at the url above does not work, but when I cloned the repository and tried it locally it did work.  Are you sure that demo is up to date?  Or is this a cross domain problem or something like that...
