### ISSUE TITLE
Stop Scrolling at Viewport Top

### ISSUE THREAD

**Issue by anubisthejackle** [oblador/angular-parallax#19]
I'm wondering if someone could provide an example where you have a list of sections, and scroll through them, but stop the container at the top of the viewport. 

Example: http://muse.adobe.com/

**Comment by lelandcope** [comment]
+1

**Comment by oblador** [comment]
@lelandcope: Try the `min` argument of [`parallaxHelper.createAnimator(easingFactor, max, min, offset);`](https://github.com/oblador/angular-parallax#createanimator).

**Comment by lelandcope** [comment]
Perfect thank you for the reply. Not sure how I missed that but its exactly what I needed.
