### ISSUE TITLE
Dist file(angular-parallax.js) should contain full dependencies syntax

### ISSUE THREAD

**Issue by timfjord** [oblador/angular-parallax#4]
Instead of

``` javascript
angular.module('duParallax.directive', ['duScroll']).
directive('duParallax',
  function(scrollPosition){
  //.....
```

should be

``` javascript
angular.module('duParallax.directive', ['duScroll']).
directive('duParallax',
  ['scrollPosition', function(scrollPosition) {
    //.....
  }]
```

**Comment by oblador** [comment]
If you look at the minified version that's included (and that's the one you're supposed to use in production). However there's no need to have it if it's not minified and in my opinion bloats the code. Makes it a tiny bit more difficult to maintain and read.

**Comment by oblador** [comment]
Closing in lack of response.

**Comment by timfjord** [comment]
Sorry for late response, was a little bit busy.
So let me add my 5 cents here.

I am RoR developer and in development environment i use non-minified version, because i want control my application and, for example, use js debugger, etc. if needed. 
Then Rails automatically handle minify process on deployment. That's why i had problem with your dist file, because due to uglify settings after deployment i got js with issues in dependencies syntax.  So it would be really great if dev version contains "full dependencies syntax" or at least we can have another one(anyway, all this version generated by grunt).

Regarding to code readability, to my mind, we should use `src` folder, because this is the source for dist version.

**Comment by oblador** [comment]
Allright I see your need, but that's something that should be fixed in your build step IMHO. 

Have you tried [ngmin-rails](https://github.com/jasonm/ngmin-rails)? Can you swap to use the .min-version instead on deployment?
