### ISSUE TITLE
Have problem with Foundation CSS

### ISSUE THREAD

**Issue by phuongnd08** [oblador/angular-parallax#9]
I'm trying to mix angular-parallax with foundation css but the animation is flickering. As soon as I remove foundation css, angular parallax works fine again. Could you have some insight?

**Comment by oblador** [comment]
Don't have any experience with foundation so I don't know. Maybe there's a css transition somewhere that interferes with the js animation? Maybe foundation is too bloated that reflows become super slow?

**Comment by phuongnd08** [comment]
I've seen people successfully used stellar.js with foundation so I guess there should be a way for angular-parallax and foundation to work together.

**Comment by phuongnd08** [comment]
I'm switching over to bootstrap and it works fine. I guess bootstrap support is good enough for me.
